'use strict';

const path = require('path');
const { log, c, readFile } = require('./util');

// The frontend team installs alongside the general team, never over it:
// different agent names (`lazysitter-fe-*`), a different command (`/lsife`),
// and its own config file. Installing both leaves you with two commands and one
// clear rule for which to use.

const FE_CONFIG = {
  team: 'frontend',
  supportedFrameworks: ['react', 'next'],
  refuseUnsupportedFramework: true,
  indexDir: '.lazysitter/index',
  rebuildIndexPerRun: true,
  rebuildIndexAfterBuildWave: true,
  supervisor: { enabled: true, mode: 'watch', perWave: true },
  loops: {
    discoveryK: 2,
    consensusRoundCap: 2,
    autofixRetryCap: 3,
    terminateOnSignatureRepeat: true,
  },
  harnessSlots: ['test', 'a11y-engine', 'render', 'bundle-measure'],
  executeKnowledgeAssertions: false,
  autoApproveGit: false,
};

// The index is derived, machine-local and regenerable. A self-ignoring
// directory keeps it out of git without touching the user's root .gitignore —
// which matters, because `.lazysitter/knowledge/` next door MUST stay tracked.
const INDEX_GITIGNORE = `# The frontend index is generated by \`lazysitter fe-index build\`.
# It is derived, machine-local and regenerable — never commit it.
# Note: this ignores ONLY .lazysitter/index/. The sibling .lazysitter/knowledge/
# directory is committed institutional memory and must stay tracked.
*
# ...except this file, so a fresh clone still ignores a locally-built index.
!.gitignore
`;

// Run artifacts — checkpoints, leases, reports, diffs, the feature text — are
// per-run working state, not source. The agents and config beside them stay
// tracked.
const RUN_ARTIFACT_GITIGNORE = `# Per-run working state written by a LazySitter run. Not source; never commit it.
runs/
RUN.lock
# Everything else here (agents, commands, config, ledgers) IS tracked.
!.gitignore
`;

function installFrontend(ctx, data, skills) {
  log.step('Frontend team → .claude/ (agents + skills + /lsife)');

  for (const agent of data.agents) {
    ctx.copy(path.join(ctx.coreDir, 'agents-fe', agent.file), `.claude/agents/${agent.file}`);
  }

  for (const skill of skills) {
    ctx.write(`.claude/skills/${skill.name}/SKILL.md`, skill.raw);
  }

  ctx.copy(path.join(ctx.coreDir, 'orchestrator.fe.claude.md'), '.claude/commands/lsife.md');
  ctx.copy(path.join(ctx.coreDir, 'roster.fe.json'), '.claude/lazysitter/roster.fe.json');
  ctx.copy(path.join(ctx.templatesDir, 'LazySitter-FE-README.md'), '.claude/lazysitter/FRONTEND-README.md');

  ctx.write('.lazysitter/index/.gitignore', INDEX_GITIGNORE);
  ctx.write('.claude/lazysitter/.gitignore', RUN_ARTIFACT_GITIGNORE);

  ctx.writePreserve(
    '.claude/lazysitter/lazysitter.fe.config.json',
    JSON.stringify(FE_CONFIG, null, 2) + '\n'
  );

  ctx.writePreserve(
    '.claude/lazysitter/PITFALL-LEDGER.md',
    readFile(path.join(ctx.coreDir, 'PITFALL-LEDGER.seed.md'))
  );
}

// Building the index is the one thing that would otherwise be a manual chore
// before the first run, so the installer just does it. Failure is never fatal:
// the orchestrator rebuilds the index at preflight on every run anyway.
function buildIndexQuietly(targetRoot) {
  const { buildIndex } = require('./fe-index/build');
  return buildIndex(targetRoot, { force: true })
    .then((res) => ({ ok: true, meta: res.meta }))
    .catch((err) => ({ ok: false, error: err.message }));
}

function printFrontendNextSteps(agentCount, skillCount, index) {
  log.info('');
  log.ok(`${c.bold('Frontend team installed')} — ${agentCount} agents, ${skillCount} skills.`);

  if (index && index.ok) {
    const m = index.meta;
    const fw = m.stack.primary;
    if (m.stack.supported) {
      log.ok(
        `${c.bold('Index built')} — ${fw.name}@${fw.version}, ${m.counts.components} components, ${m.counts.hooks} hooks, ${m.counts.utils} utils, ${m.counts.findings} findings.`
      );
    } else {
      log.warn(`This repo is ${fw ? fw.name : 'not React/Next'} — the frontend team will refuse to run here.`);
      log.info(`  ${c.dim('Use the general team instead: /lsi')}`);
    }
  } else if (index) {
    log.warn(`Index not built yet (${index.error}) — the first /lsife run builds it automatically.`);
  }

  log.info('');
  log.info(`  ${c.bold('You are done. In Claude Code, run:')}`);
  log.info(`     ${c.bold('/lsife <what you want>')}`);
  log.info(`     ${c.dim('e.g. /lsife Add a CSV export button to the analytics dashboard')}`);
  log.info('');
  log.info(`  ${c.dim('Nothing else to configure. The team keeps its own index and run state up to date.')}`);
  log.info(`  ${c.dim('React/Next only — for backend or full-stack work use the general team: /lsi')}`);
  log.info('');
}

module.exports = { installFrontend, printFrontendNextSteps, buildIndexQuietly, FE_CONFIG };
