'use strict';

const path = require('path');
const { log, c, readFile } = require('./util');

// The frontend team installs alongside the general team, never over it:
// different agent names (`lazysitter-fe-*`), a different command (`/lsife`),
// and its own config file. Installing both leaves you with two commands and one
// clear rule for which to use.

const FE_CONFIG = {
  team: 'frontend',
  supportedFrameworks: ['react', 'next'],
  refuseUnsupportedFramework: true,
  indexDir: '.lazysitter/index',
  rebuildIndexPerRun: true,
  rebuildIndexAfterBuildWave: true,
  supervisor: { enabled: true, mode: 'watch', perWave: true },
  loops: {
    discoveryK: 2,
    consensusRoundCap: 2,
    autofixRetryCap: 3,
    terminateOnSignatureRepeat: true,
  },
  harnessSlots: ['test', 'a11y-engine', 'render', 'bundle-measure'],
  executeKnowledgeAssertions: false,
  autoApproveGit: false,
};

// The index is derived, machine-local and regenerable. A self-ignoring
// directory keeps it out of git without touching the user's root .gitignore —
// which matters, because `.lazysitter/knowledge/` next door MUST stay tracked.
const INDEX_GITIGNORE = `# The frontend index is generated by \`lazysitter fe-index build\`.
# It is derived, machine-local and regenerable — never commit it.
# Note: this ignores ONLY .lazysitter/index/. The sibling .lazysitter/knowledge/
# directory is committed institutional memory and must stay tracked.
*
# ...except this file, so a fresh clone still ignores a locally-built index.
!.gitignore
`;

// Run artifacts — checkpoints, leases, reports, diffs, the feature text — are
// per-run working state, not source. The agents and config beside them stay
// tracked.
const RUN_ARTIFACT_GITIGNORE = `# Per-run working state written by a LazySitter run. Not source; never commit it.
runs/
RUN.lock
# Everything else here (agents, commands, config, ledgers) IS tracked.
!.gitignore
`;

function installFrontend(ctx, data, skills) {
  log.step('Frontend team → .claude/ (agents + skills + /lsife)');

  for (const agent of data.agents) {
    ctx.copy(path.join(ctx.coreDir, 'agents-fe', agent.file), `.claude/agents/${agent.file}`);
  }

  for (const skill of skills) {
    ctx.write(`.claude/skills/${skill.name}/SKILL.md`, skill.raw);
  }

  ctx.copy(path.join(ctx.coreDir, 'orchestrator.fe.claude.md'), '.claude/commands/lsife.md');
  ctx.copy(path.join(ctx.coreDir, 'roster.fe.json'), '.claude/lazysitter/roster.fe.json');
  ctx.copy(path.join(ctx.templatesDir, 'LazySitter-FE-README.md'), '.claude/lazysitter/FRONTEND-README.md');

  ctx.write('.lazysitter/index/.gitignore', INDEX_GITIGNORE);
  ctx.write('.claude/lazysitter/.gitignore', RUN_ARTIFACT_GITIGNORE);

  ctx.writePreserve(
    '.claude/lazysitter/lazysitter.fe.config.json',
    JSON.stringify(FE_CONFIG, null, 2) + '\n'
  );

  ctx.writePreserve(
    '.claude/lazysitter/PITFALL-LEDGER.md',
    readFile(path.join(ctx.coreDir, 'PITFALL-LEDGER.seed.md'))
  );
}

function printFrontendNextSteps(agentCount, skillCount) {
  log.info('');
  log.ok(`${c.bold('Frontend team installed')} — ${agentCount} agents, ${skillCount} skills.`);
  log.info('');
  log.info(`  ${c.bold('1.')} Build the index first — every agent queries it instead of grepping:`);
  log.info(`     ${c.dim('npx lazysitter fe-index build')}`);
  log.info(`  ${c.bold('2.')} Run the team in Claude Code:`);
  log.info(`     ${c.bold('/lsife <UI feature request>')}   ${c.dim('e.g. /lsife Add a CSV export button to the analytics dashboard --dry-run')}`);
  log.info('');
  log.info(`  ${c.dim('React and Next.js only — the run halts on any other framework by design.')}`);
  log.info(`  ${c.dim('For backend or full-stack work use the general team: /lsi')}`);
  log.info('');
}

module.exports = { installFrontend, printFrontendNextSteps, FE_CONFIG };
