'use strict';

const path = require('path');
const { log, readFile } = require('./util');
const fm = require('./frontmatter');

const SKILL_DIR = '.codex/skills/lazysitter';

function installCodex(ctx, data) {
  log.step('Codex adapter → .codex/skills/lazysitter/');

  const orch = readFile(path.join(ctx.coreDir, 'orchestrator.codex.md'));
  ctx.write(`${SKILL_DIR}/SKILL.md`, orch);

  const { body: orchBody } = fm.parse(orch);
  ctx.write(`${SKILL_DIR}/orchestrator.md`, orchBody.trimStart());

  for (const agent of data.agents) {
    ctx.write(`${SKILL_DIR}/agents/${agent.file}`, roleFile(agent));
    ctx.write(`${SKILL_DIR}/agents/${agent.name}.meta`, metaFile(agent));
  }

  ctx.copy(path.join(ctx.coreDir, 'codex', 'run-agent.sh'), `${SKILL_DIR}/run-agent.sh`, {
    exec: true,
  });
  ctx.copy(path.join(ctx.coreDir, 'codex', 'run-agent.ps1'), `${SKILL_DIR}/run-agent.ps1`);

  ctx.writePreserve(
    `${SKILL_DIR}/PITFALL-LEDGER.md`,
    readFile(path.join(ctx.coreDir, 'PITFALL-LEDGER.seed.md'))
  );

  ctx.writePreserve(`${SKILL_DIR}/models.env`, readFile(path.join(ctx.coreDir, 'codex', 'models.env')));
  ctx.writePreserve(
    `${SKILL_DIR}/lazysitter.config.json`,
    readFile(path.join(ctx.coreDir, 'codex', 'lazysitter.config.json'))
  );

  ctx.mergeMarkedBlock('AGENTS.md', readFile(path.join(ctx.coreDir, 'codex', 'AGENTS.lazysitter.md')));
}

function roleFile(agent) {
  const header = `<!-- LazySitter role: ${agent.name} · tier=${agent.tier} · codex sandbox=${agent.codexSandbox} · approval=${agent.codexApproval} -->\n\n`;
  return header + agent.body.trimStart();
}

function metaFile(agent) {
  return (
    `# Generated by the LazySitter installer from core/roster.json — do not hand-edit.\n` +
    `TIER=${agent.tier}\n` +
    `SANDBOX=${agent.codexSandbox}\n` +
    `APPROVAL=${agent.codexApproval}\n` +
    `DISTINCT_MODEL=${agent.distinctModel ? '1' : '0'}\n`
  );
}

module.exports = { installCodex };
